mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: mqduong+1@amazon.com
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: mqduong+logarchive@amazon.com
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: mqduong+audit@amazon.com
    organizationalUnit: Security
    warm: false

workloadAccounts:
  - name: Infrastructure1
    description: The Infrastructure 1 account.
    email: mqduong+infrastructure1@amazon.com
    organizationalUnit: Infrastructure
  - name: Infrastucture2
    description: The Infrastructure 2 account.
    email: mqduong+infrastructure2@amazon.com
    organizationalUnit: Infrastructure
  - name: Sandbox1
    description: The Sandbox 1 account.
    email: mqduong+sandbox1@amazon.com
    organizationalUnit: Sandbox
  - name: Sandbox2
    description: The Sandbox 2 account.
    email: mqduong+sandbox2@amazon.com
    organizationalUnit: Sandbox
  - name: Sandbox3
    description: The Sandbox 3 account.
    email: mqduong+sandbox3@amazon.com
    organizationalUnit: Sandbox
  - name: Sandbox4
    description: The Sandbox 4 account.
    email: mqduong+sandbox4@amazon.com
    organizationalUnit: Sandbox
  - name: AFTManagement
    description: The management account for AFT.
    email: mqduong+aftmanagement@amazon.com
    organizationalUnit: AFT

    

